### ISSUE TITLE
NoOne - Pssible DoS atack

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-napier-update-judging#1]
NoOne

medium

# Pssible DoS atack

## Vulnerability Detail
The function [stake_](https://github.com/sherlock-audit/2024-05-napier-update/blob/main/napier-uups-adapters/src/adapters/renzo/RenzoAdapter.sol#L60) doesn`t check the current stake limit
## Impact
It will lead to DoS atack
## Code Snippet
[RenzoAdapter.sol - (function _stake)](https://github.com/sherlock-audit/2024-05-napier-update/blob/main/napier-uups-adapters/src/adapters/renzo/RenzoAdapter.sol#L60)
## Tool used

Manual Review

## Recommendation
Check the current  stake limit before staking like in [PufETHAdapter.sol - function _stake](https://github.com/sherlock-audit/2024-05-napier-update/blob/main/napier-uups-adapters/src/adapters/puffer/PufETHAdapter.sol#L66)

**Comment by Jelev123** [comment]
Why this issue is rewarded https://github.com/sherlock-audit/2024-05-napier-update-judging/issues/24 , but mine is not

**Comment by Jelev123** [comment]
this is also rewarded https://github.com/sherlock-audit/2024-05-napier-update-judging/issues/39

**Comment by Jelev123** [comment]
especially this one https://github.com/sherlock-audit/2024-05-napier-update-judging/issues/18

**Comment by Jelev123** [comment]
Escalate
The issue that i submit is exactly like https://github.com/sherlock-audit/2024-05-napier-update-judging/issues/18 why is not dublicate of it

**Comment by sherlock-admin3** [comment]
> Escalate
> The issue that i submit is exactly like https://github.com/sherlock-audit/2024-05-napier-update-judging/issues/18 why is not dublicate of it 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by Jelev123** [comment]
Escalate
The issue that i submit is exactly like https://github.com/sherlock-audit/2024-05-napier-update-judging/issues/18 why is not dublicate of it

**Comment by sherlock-admin3** [comment]
> Escalate
> The issue that i submit is exactly like https://github.com/sherlock-audit/2024-05-napier-update-judging/issues/18 why is not dublicate of it

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by Jelev123** [comment]
Escalate
The issue that i submit is exactly like https://github.com/sherlock-audit/2024-05-napier-update-judging/issues/18 why is not dublicate of it

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
