### ISSUE TITLE
yamato - `EETHAdapter` wrongfully valuates `EETH : ETH` at 1:1 rate

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-napier-update-judging#12]
yamato

medium

# `EETHAdapter` wrongfully valuates `EETH : ETH` at 1:1 rate

## Summary
Contract wrongfully assumes EETH has same value as ETH

## Vulnerability Detail
This is the `totalAssets` function within the EETHAdapter, which is responsible to calculate the total value in the contract (denominated in ETH)
```solidity
    function totalAssets() public view override returns (uint256) {
        uint256 eEthBalance = EETH.balanceOf(address(this));
        return totalQueueEth + bufferEth + eEthBalance;
    }
```

As it can be seen it valuates `EETH` at 1:1 rate.

At the time of this report, `EETH` equals to 1.03851 ETH.

The difference is not insignificant and should be considered. The share rate can be fetched directly from the etherfi `LIQUIDITY_POOL` contract

## Impact
Wrong accounting

## Code Snippet
https://github.com/sherlock-audit/2024-05-napier-update/blob/main/napier-v1/src/adapters/etherfi/EETHAdapter.sol#L129

## Tool used

Manual Review

## Recommendation
fix accounting

**Comment by massun-onibakuchi** [comment]
doc says EETH is rebase token. we assume share price of EETH is 1 in units of ETH in the same way as stETHAdapater.

https://etherfi.gitbook.io/etherfi/ether.fi-whitepaper/technical-documentation#eeth
