### ISSUE TITLE
djaner - `MetapoolIRouter.sol` lacks withdrawal and swap functionalities for YT tokens

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-napier-update-judging#14]
djaner

high

# `MetapoolIRouter.sol` lacks withdrawal and swap functionalities for YT tokens

## Summary

Users' YT tokens are indefinitely locked within the contract.

## Vulnerability Detail

The current implementation of `MetapoolIRouter.sol` presents a critical issue: it doesn't include functions for withdrawing or swapping YT tokens. Consequently, users' YT tokens are permanently locked within the contract, rendering them inaccessible. This issue needs to be promptly addressed to ensure the functionality and usability of the `MetapoolIRouter.sol` contract.

## Impact

The lack of essential functionalities impedes users from utilizing the contract as intended. The inability to withdraw accrued interest diminishes user motivation to engage with the application.

## Code Snippet

[MetapoolRouter.sol](https://github.com/sherlock-audit/2024-05-napier-update/blob/main/metapool-router/src/MetapoolRouter.sol#L29)

```javascript
contract MetapoolRouter is ReentrancyGuard, IFlashLoanRecipient, IMetapoolRouter {}
```

## Tool Used

Manual Review

## Recommendation

Implement withdrawal and swap functionalities for YT tokens to enable users to access their interest and ensure the usability of the contract.

**Comment by massun-onibakuchi** [comment]
I listed up known issues/acceptable  that should not result in a valid finding here. 

https://www.notion.so/napier-labs/Napier-Finance-LST-LRT-integrations-604eefb86a20475c804966a0b8a3bdbb?pvs=4#4cffe65ae2c14c3da1b98f28c23798ff

> 1.  The reason why `MetapoolRouter` doesn’t have method to swap YT for ETH.
> - We found it’s impossible to implement on the current version. Users can exit position after the maturity. These kinds of findings would be not valid.
