### ISSUE TITLE
djaner - Oracle response not checked for stale prices

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-napier-update-judging#16]
djaner

medium

# Oracle response not checked for stale prices

## Summary

`RsETHAdapter` don't check for stale prices.

## Vulnerability Detail

Oracle call in `RsETHAdapter:totalAssets` don't check for stale prices.

## Impact

Oracle price feeds can become stale due to a variety of [reasons](https://ethereum.stackexchange.com/questions/133242/how-future-resilient-is-a-chainlink-price-feed/133843#133843). Using a stale price will result in incorrect calculations in most of the key functionality of `RsETHAdapter` contract.

## Code Snippet

(https://github.com/sherlock-audit/2024-05-napier-update/blob/main/napier-uups-adapters/src/adapters/kelp/RsETHAdapter.sol#L107)

```javascript
function totalAssets() public view override returns (uint256) {
        LSTAdapterStorage storage $ = _getStorage();
        return $.totalQueueEth + $.bufferEth + (RSETH.balanceOf(address(this)) * RSETH_ORACLE.rsETHPrice()) / 1e18;
    }
```

## Tool used

Manual Review

## Recommendation

Make sure the prices returned by the `RSETH_ORACLE` are not stale.

Duplicate of #80

**Comment by massun-onibakuchi** [comment]
rsETH oracle itself takes care of such risks. The oracle is kind  of average of various sources and the oracle checks whether it is fresh. so we assume it is safe enough.
