### ISSUE TITLE
Bauer - `BEDROCK_STAKING.mint()` lacks slippage protection

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-napier-update-judging#32]
Bauer

high

# `BEDROCK_STAKING.mint()` lacks slippage protection

## Summary

In the `_stake()` function of `UniETHAdapter`, the protocol calls `BEDROCK_STAKING.mint()` to stake ETH. However, the parameter for slippage protection passed during the stake is set to 0, meaning there is no slippage protection in place. This makes it easy for users to suffer from sandwich attacks, resulting in financial losses

## Vulnerability Detail
In the `UniETHAdapter._stake()` function, the protocol calls `BEDROCK_STAKING.mint()` to stake ETH into the staking contract. 
```solidity
    function _stake(uint256 stakeAmount) internal override returns (uint256) {
        if (stakeAmount == 0) return 0;

        IWETH9(Constants.WETH).withdraw(stakeAmount);
        uint256 _balance = UNIETH.balanceOf(address(this));
        BEDROCK_STAKING.mint{value: stakeAmount}({minToMint: 0, deadline: block.timestamp + 1});
        uint256 minted = UNIETH.balanceOf(address(this)) - _balance;
        if (minted == 0) revert InvariantViolation();

        return stakeAmount;
    }

```

The `mint()` function has a parameter `minToMint` for slippage protection. 

```solidity
    /**
     * @dev mint xETH with ETH
     */
    function mint(uint256 minToMint, uint256 deadline) external payable nonReentrant whenNotPaused returns(uint256 minted) {
        _require(block.timestamp < deadline, "USR001");
        _require(msg.value > 0, "USR002");

        // track balance
        _balanceIncrease(msg.value);

        // mint xETH while keeping the exchange ratio invariant
        uint256 totalXETH = IERC20(xETHAddress).totalSupply();
        uint256 totalEthers = currentReserve();
        uint256 toMint = 1 * msg.value;  // default exchange ratio 1:1

        if (totalEthers > 0) { // avert division overflow
            toMint = totalXETH * msg.value / totalEthers;
        }

        _require(toMint >= minToMint, "USR004");


```

However, the protocol passes 0 as the `minToMint` value, meaning there is no slippage protection. This makes the mint operation highly susceptible to sandwich attacks, resulting in outcomes that do not meet the user's expectations and causing financial losses for the user.
The `RSETH_DEPOSIT_POOL.depositETH()` function in the `RsETHAdapter` contract also suffers from the same issue.
## Impact
The user suffers financial losses due to a sandwich attack.

## Code Snippet
https://github.com/sherlock-audit/2024-05-napier-update/blob/main/napier-v1/src/adapters/bedrock/UniETHAdapter.sol#L78

## Tool used

Manual Review

## Recommendation
The recommended fix is to set a value for slippage protection.

**Comment by massun-onibakuchi** [comment]
we know the deadline and min amount params are not compatible with adapter. but on our side, users interact with TrancheRouter.sol in v1-pool repo implementing such slippage protection.
https://github.com/sherlock-audit/2024-05-napier-update/blob/main/metapool-router/lib/v1-pool/src/TrancheRouter.sol
